// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireApiDto } from "./WireApiDto";

/**
 * A known provider: the union of configured providers and the bundled
 * catalog. `configured` is true when present in `config.model_providers`;
 * `is_default` is true when its id equals `config.model_provider_id`.
 */
export type InterpreterProvider = { id: string, name: string, baseUrl?: string, wireApi: WireApiDto, envKey?: string, configured: boolean, isDefault: boolean, };
