// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire protocol that a provider speaks. Mirror of
 * `codex_model_provider_info::WireApi` so this crate does not depend on it.
 */
export type WireApiDto = "responses" | "chat" | "messages";
